name: 'Doxygen Generator'
description: 'Generate documentation for Moodle using Doxygen'
inputs:
  doxyfile-path:
    description: 'Path to Doxyfile'
    required: false
    default: './phpdocs/Doxyfile'
  working-directory:
    description:  'Working directory'
    required: false
    default: '.'
  env-file:
    description: 'Environemnt variable file to pass'
    required: false
    default: '.env'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doxyfile-path }}
    - ${{ inputs.working-directory }}
    - ${{ inputs.env-file }}
